services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - broker-kafka

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092  # Alterado de localhost para kafka
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - broker-kafka

  kafkaproducer:
    build:
      context: ./kafkaProducer
    container_name: kafkaproject-kafkaproducer
    image: kafkaproject-kafkaproducer
    ports:
      - "8080:8080"
    environment:
      BOOTSTRAP_SERVER: kafka:9092
    depends_on:
      - kafka
    networks:
      - broker-kafka

  kafkaconsumer:
    build:
      context: ./kafkaConsumer
    container_name: kafkaproject-kafkaconsumer
    image: kafkaproject-kafkaconsumer
    ports:
      - "8081:8081"
    environment:
      BOOTSTRAP_SERVER: kafka:9092
    depends_on:
      - kafkaproducer
    networks:
      - broker-kafka

  frontend:
    build:
      context: ./frontend
    container_name: kafkaproject-frontend
    image: kafkaproject-frontend
    ports:
      - "80:80"
    depends_on:
      - kafkaconsumer
    networks:
      - broker-kafka

networks:
  broker-kafka:
    driver: bridge
